name: Deploy to Railway

on:
  push:
    branches:
      - main

env:
  RAILWAY_PROJECT_ID: ${{ secrets.RAILWAY_PROJECT_ID }}
  TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Railway CLI
        run: npm install -g @railwayapp/cli

      - name: Deploy to Railway
        run: railway deploy --service rpowlite-bot --commit-hash ${{ github.sha }}
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
